title: Smoothed Particle Hydrodynamics Manual
show_downloads: false
theme: jekyll-theme-minimal
#repository: AhmedSalih3d/SmoothedParticleHydrodynamicsManual
#absolute_url: "https://ahmedsalih3d.github.io/SmoothedParticleHydrodynamicsManual/"
